function ppi_processing_nvs(inp)

tag = 'nvs';

spm_dir = fullfile(inp.out_dir,['spm_' tag]);


% Split the ROI file into individual images for PPI -
% Load, split into individual images for gppi, sanitize ROI names
roi_dir = fullfile(inp.out_dir,['roiwkdir_' tag]);
mkdir(roi_dir);
copyfile(inp.ppiroi_niigz, roi_dir)
[~,n,e] = fileparts(inp.ppiroi_niigz);
gunzip(fullfile(roi_dir,[n e]))
ppiroi_nii = fullfile(roi_dir,n);
V = spm_vol(ppiroi_nii);
Yroi = spm_read_vols(V);
roiinds = unique(Yroi(:));
roiinds = roiinds(roiinds~=0);
roilabels = readtable(inp.ppiroilabels_tsv,'FileType','text','Delimiter','tab');
if sort(roilabels.index)~=sort(roiinds)
    error('Mismatch in ROI indices')
end

%% FIXME sanitize ROI names, create individual ROI files
disp(roilabels)
return


% Basic PPI analysis parameters
% There is a bug when specifying 'outdir', so use the default
P = struct( ...
    'subject', 'testsubj', ...
    'directory', spm_dir, ...
    'VOI', [roi_dir '/BNST_L.nii'], ...
    'Region', 'BNST_L', ...
    'analysis', 'psy', ...
    'method', 'cond', ...
    'extract', 'eig', ...
    'contrast', 0, ...
    'Estimate', 1, ...
    'equalroi', 1, ...
    'FLmask', 0, ...
    'CompContrasts', 1, ...
    'Weighted', 0, ...
    'SPMver', '12', ...
    'preservevarcorr', 1 ...
    );


% Tasks to include in PPI analyses
P.Tasks = { ...
    '1' ...
    'CueNeutral' ...
    'CueFear' ...
    'CueUnknown' ...
    'ImageNeutral' ...
    'ImageFear' ...
    'ImageUnknown_Neutral' ...
    'ImageUnknown_Fear' ...
    };
P.Weights = [];


% Contrasts, one per task
for c = 2:numel(P.Tasks)
    P.Contrasts(c-1) = struct( ...
        'left', {P.Tasks(c)}, ...
        'right', {{'none'}}, ...
        'STAT', 'T' ...
        );
end

save([pwd '/../OUTPUTS/BSNT_L_PPI.mat'],'P')
PPPI([pwd '/../OUTPUTS/BSNT_L_PPI.mat'])

