% This script will test the matlab pipeline from the matlab command line -
% very useful for making sure it works before we bother to compile.

matlab_entrypoint( ...
	'fmriprep1_dir','../../INPUTS/fmriprep1', ...
	'fmriprep2_dir','../../INPUTS/fmriprep2', ...
	'fmriprep3_dir','../../INPUTS/fmriprep3', ...
	'fmriprep4_dir','../../INPUTS/fmriprep4', ...
	'eprime_csv','../../OUTPUTS/eprime.csv', ...
	'hpf_sec','300', ...
	'fwhm_mm','6', ...
	'out_dir','../../OUTPUTS' ...
	);
