% This script will test the matlab pipeline from the matlab command line -
% very useful for making sure it works before we bother to compile.

addpath(pwd)
addpath([pwd '/../../rois'])

matlab_entrypoint( ...
    'fmriprep1_dir',[pwd '/../../INPUTS/fmriprep1'], ...
    'fmriprep2_dir',[pwd '/../../INPUTS/fmriprep2'], ...
    'fmriprep3_dir',[pwd '/../../INPUTS/fmriprep3'], ...
    'fmriprep4_dir',[pwd '/../../INPUTS/fmriprep4'], ...
    'eprime_csv',[pwd '/../../OUTPUTS/eprime.csv'], ...
    'hpf_sec','300', ...
    'fwhm_mm','6', ...
    'out_dir',[pwd '/../../OUTPUTS'] ...
    );

%    'ppiroi_niigz', [pwd '/../../rois/space-MNI152NLin6Asym_atlas-BNST_dseg.nii.gz'], ...
%    'ppiroilabels_tsv', [pwd '/../../rois/atlas-BNST_dseg.tsv'] ...
