
wd = pwd;

timings = get_timings('../../OUTPUTS/eprime.csv');

inp = struct( ...
    'fwhm_mm', '6', ...
    'hpf_sec', '300', ...
	'motpar_txt', {{[pwd '/../../OUTPUTS/motpar1.txt'],[pwd '/../../OUTPUTS/motpar2.txt'],[pwd '/../../OUTPUTS/motpar3.txt'],[pwd '/../../OUTPUTS/motpar4.txt']}}, ...
	'out_dir', [pwd '/../../OUTPUTS'], ...
	'timings', {timings}, ...
	'fmri_nii', {{[pwd '/../../OUTPUTS/fmri1.nii'],[pwd '/../../OUTPUTS/fmri2.nii'],[pwd '/../../OUTPUTS/fmri3.nii'],[pwd '/../../OUTPUTS/fmri4.nii']}}, ...
	'biasnorm_nii', [pwd '/../../OUTPUTS/biasnorm.nii'] ...
	);

first_level_stats_nvs(inp);

cd(wd);
