
wd = pwd;

timings = get_timings('../../OUTPUTS/eprime.csv');

inp = struct( ...
	'hpf_sec', '300', ...
	'motpar_txt', {{'../../OUTPUTS/motpar1.txt','../../OUTPUTS/motpar2.txt','../../OUTPUTS/motpar3.txt','../../OUTPUTS/motpar4.txt'}}, ...
	'out_dir', '../../OUTPUTS', ...
	'timings', {timings}, ...
	'fmri_nii', {{'../../OUTPUTS/sfmri1.nii','../../OUTPUTS/sfmri2.nii','../../OUTPUTS/sfmri3.nii','../../OUTPUTS/sfmri4.nii'}}, ...
	'biasnorm_nii', '../../OUTPUTS/biasnorm.nii' ...
	);

first_level_stats_nvs(inp);

cd(wd);
