% This script will test the matlab pipeline from the matlab command line -
% very useful for making sure it works before we bother to compile.

addpath(pwd)
addpath([pwd '/../external/spm8_r6313/spm8'])
addpath([pwd '/../external/spm8_r6313/spm8/toolbox/PPPI'])
addpath([pwd '/../external/gppi'])
addpath([pwd '/../../rois'])

matlab_entrypoint( ...
    'fmriprep1_dir',[pwd '/../../INPUTS/fmriprep1'], ...
    'fmriprep2_dir',[pwd '/../../INPUTS/fmriprep2'], ...
    'fmriprep3_dir',[pwd '/../../INPUTS/fmriprep3'], ...
    'fmriprep4_dir',[pwd '/../../INPUTS/fmriprep4'], ...
    'eprime_csv',[pwd '/../../INPUTS/eprime.csv'], ...
    'ppiroi_niigz', 'space-MNI152NLin6Asym_atlas-BNSTamyg_dseg.nii.gz', ...
    'ppiroilabels_tsv', 'atlas-BNSTamyg_dseg.tsv', ...
    'hpf_sec','300', ...
    'input_fwhm_mm','0', ...
    'ppicon_fwhm_mm','6', ...
    'out_dir',[pwd '/../../OUTPUTS'] ...
    );

